#!/usr/bin/env bash
set -e -o pipefail

echo "Test compiler against well known repos."

TARGETS='@com_google_googletest//... @com_github_google_benchmark//... @com_google_absl//... @com_google_protobuf//:protoc'
STATIC_ANALYZER_TARGETS='@com_google_protobuf//:protoc'

# Test compilation of well known repositories
bazel test $TARGETS --test_tag_filters=-benchmark

bazel build $TARGETS

bazel build $STATIC_ANALYZER_TARGETS --aspects //tools/clang_tidy:clang_tidy.bzl%clang_tidy_aspect --output_groups=report 